# Generated by Django 4.0.4 on 2022-04-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('sensor', models.CharField(max_length=50)),
                ('resolution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
