# Generated by Django 4.0.4 on 2022-04-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_camera_lens_mount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lens_mount', models.CharField(max_length=50)),
                ('focal_length', models.CharField(max_length=50)),
                ('aperture', models.CharField(max_length=30)),
            ],
        ),
    ]
