# Generated by Django 4.0.4 on 2022-04-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_lens'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='lens',
            field=models.ManyToManyField(to='main_app.lens'),
        ),
    ]
