# Generated by Django 4.0.4 on 2022-04-28 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_alter_recall_options_alter_recall_date_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
